language: c++
dist: trusty
install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get update -qq
  - sudo apt-get install g++ cmake libboost-all-dev pandoc zlib1g-dev libbz2-dev libsqlite3-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j && make test
